title:              Chestnut Blog
email:              cheng_junhan@outlook.com
description:        一个野生的游戏程序猿
author:             Chestnut
baseurl:            ""
url:                "https://chestnut-f.github.io"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Build settings
markdown:           kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

highlighter: pygments
permalink: pretty
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个野生的游戏程序猿"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`