title:              First Blog
email:              cheng_junhan@outlook.com
description:        A Test Blog Theme by Start Bootstrap
author:             Chestnut
baseurl:            "/clean-blog-jekyll"
url:                "https://chestnut-f.github.io"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
